### ISSUE TITLE
GHCR Image is not public

### ISSUE THREAD

**Issue by BeryJu** [DazWilkin/linode-exporter#43]
While creating #42 and #41, I noticed that the GHCR container image is not public:

```
✖ docker pull ghcr.io/dazwilkin/linode-exporter:b4e6fabbbd64132b4f08a164cfc42365ae859d50
Error response from daemon: denied
```

In the same vein, it might make sense to publish a `:latest` image? Or any kind versioned tag but that would require a more complicated build process

**Comment by DazWilkin** [comment]
Thanks for pointing this out.

I've made the image public.

I would prefer to consider publishing releases than `latest`.

**Comment by DazWilkin** [comment]
Thank you for the PRs!

I've a personal commitment tomorrow but I'll review these over the weekend.

**Comment by DazWilkin** [comment]
Okay to close this issue?

**Comment by BeryJu** [comment]
Oh yeah
